/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_litongjava_media_MediaCodec */

#ifndef _Included_com_litongjava_media_MediaCodec
#define _Included_com_litongjava_media_MediaCodec
#ifdef __cplusplus
extern "C" {
#endif
#undef com_litongjava_media_MediaCodec_CODEC_PCMU
#define com_litongjava_media_MediaCodec_CODEC_PCMU 0L
#undef com_litongjava_media_MediaCodec_CODEC_PCMA
#define com_litongjava_media_MediaCodec_CODEC_PCMA 8L
#undef com_litongjava_media_MediaCodec_CODEC_G722
#define com_litongjava_media_MediaCodec_CODEC_G722 9L
/*
 * Class:     com_litongjava_media_MediaCodec
 * Method:    createEncoder
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_litongjava_media_MediaCodec_createEncoder
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_litongjava_media_MediaCodec
 * Method:    destroyEncoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litongjava_media_MediaCodec_destroyEncoder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litongjava_media_MediaCodec
 * Method:    encodeDirect
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_litongjava_media_MediaCodec_encodeDirect
  (JNIEnv *, jclass, jlong, jobject, jint, jobject);

/*
 * Class:     com_litongjava_media_MediaCodec
 * Method:    createDecoder
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_litongjava_media_MediaCodec_createDecoder
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     com_litongjava_media_MediaCodec
 * Method:    destroyDecoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_litongjava_media_MediaCodec_destroyDecoder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_litongjava_media_MediaCodec
 * Method:    decodeDirect
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_litongjava_media_MediaCodec_decodeDirect
  (JNIEnv *, jclass, jlong, jobject, jint, jobject);

/*
 * Class:     com_litongjava_media_MediaCodec
 * Method:    getPcmSamplesPer20ms
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_litongjava_media_MediaCodec_getPcmSamplesPer20ms
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_litongjava_media_MediaCodec
 * Method:    getEncodedBytesPer20ms
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_litongjava_media_MediaCodec_getEncodedBytesPer20ms
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
